### ISSUE TITLE
Renaming a directory or file "How To"?

### ISSUE THREAD

**Issue by datovy-edam** [KristofferStrube/Blazor.FileSystem#8]
With this library I have done all needed operations, now if I change the name of an Entry (a directory or file), how do I persist the change?

I guess that holding to the info, removing and creating a new one will do the job, but is there is any option within the library can you point me to it?

**Comment by KristofferStrube** [comment]
Hey @datovy-edam, that is not a part of the API out of the box. The easiest solution is to get a `File` from an existing `FileSystemFileHandle` and then writing that to a new `FileSystemFileHandle`.

I don't know of an easy way to do this for a directory structure apart from traversing all folders and sub-folders and copying them systematically.

**Comment by datovy-edam** [comment]
Thanks for your quick response, I will try to find a way to do this.
